package utils;

public enum Header {
    ADD_STUDENT, DELETE_STUDENT, UPDATE_STUDENT, GET_ALL_STUDENT, GET_STUDENT_ID, FILTER_STUDENTS_NAME, SORT_STUDENTS_ASC, GET_STUDENTS_PASSED, GET_MOST_PROBLEMS,
    ADD_PROBLEM, DELETE_PROBLEM, UPDATE_PROBLEM, GET_ALL_PROBLEMS, GET_PROBLEM_ID, FILTER_PROBLEMS_SCORE, SORT_PROBLEMS_DESC, GET_PROBLEM_MOST_TIMES,
    ADD_ASSIGNMENT, DELETE_ASSIGNMENT, UPDATE_ASSIGNMENT, GET_ALL_ASSIGNMENTS, FILTER_ASSIGNMENTS_GRADE, SORT_ASSIGNMENTS_ASC
}
